version: 2
updates:
- package-ecosystem: gomod
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "09:00"
- package-ecosystem: "github-actions"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "09:00"
