name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    # Can't build as there is no opengl installation on CI
    # - name: Build
    #   run: go mod tidy -v -compat=1.17 && go build -v ./...

    - name: Test
      run: go mod tidy -v -compat=1.17 && go test -v ./...
