name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Install Ebiten dependencies
      run: sudo apt-get update && sudo apt-get install -y libx11-dev libgl1-mesa-dev libasound2-dev libgles2-mesa-dev libalut-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev xvfb

    - name: Build
      run: go build -v ./...

    - name: Go test (with virtual display)
      run: xvfb-run go test -v ./...
